### ISSUE TITLE
Add configurable http sleep setting

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#235]
QNL (and potentially other providers) require slower access to their OAI-PMH server (see #200). It should be possible to set an option in the Intake collection `args` to indicate how many seconds to `wait` between HTTP requests, and then adjust the OAI Driver to look for and follow the setting when found.

```yaml
metadata:
  version: 1
  data_path: qnl
  schedule: "40 11 * * *"
sources:
  qnl:
    driver: oai_xml
    args:
      collection_url: https://api.qdl.qa/api/oaipmh
      metadata_prefix: mods_no_ocr
      wait: 2
    metadata:
      data_path: qnl/british-library-combined
      post_harvest: "merge_records"
      config: qnl_config
      fields:
        id:
          path: "//header:identifier"
          namespace:
            header: "http://www.openarchives.org/OAI/2.0/"
          optional: True
```
